---
- name: Chapter02 - Playbook Modules
  hosts: servers
  become: true
  tasks:
    - name: Update hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.1.1 server01"
