---
- name: Chapter03 - Variables and Facts
  hosts: servers
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Update hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ host_ip }} {{ host_name }}"
